version: '3.9'
services:
  web:
    image: nginx
    volumes:
      - ./build:/home/app
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources/socket.conf:/etc/nginx/conf.d/default1.conf
    network_mode: "host"
  stun:
    build:
      context: ../peerjs-room
      dockerfile: ../peerjs-room/Dockerfile
    depends_on:
    - web
